### ISSUE TITLE
Option to disabled adding account to list when stuck at Steam Guard

### ISSUE THREAD

**Issue by UnselectedGitIgnore** [sag-enhanced/sage-issues#48] opened 2024-06-22 23:02 UTC
### Describe the feature

When the account creation is stuck at Steam Guard, it has already added the account to the list. Add the option to disable adding it to the list. 
![mstsc_wAxKdD918I](https://github.com/sag-enhanced/sage-issues/assets/165699636/a1b34045-c97e-490d-afd2-64946782a1cc)

### Use case

When creating accounts in large amounts and you only want accounts without SteamGuard enabled.

**Comment by Le0Developer** [comment] 2024-06-23 15:08
I think it'd be better to fix the root cause of the failure?
Anything that does not have clear failure code (eg A101, B4) is an internal error that should be fixed.

**Comment by Le0Developer** [comment] 2024-06-27 14:49
Stale

**Closed as not planned by Le0Developer** 2024-06-27 14:49 UTC
Labels: Area: Frontend
